M48
; DRILL file KiCad 10.0.6 date 2026-10-06T17:14:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-06T17:14:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X70.0Y-76.82
X84.5Y-76.855
T2
X59.5Y-40.5
X59.5Y-77.5
X102.25Y-46.622
X102.25Y-58.052
X106.0Y-40.5
X106.0Y-77.5
M30
