M48
; DRILL file KiCad 10.0.6 date 2026-10-07T14:51:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T14:51:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.251
%
G90
G05
T1
X127.0Y-75.8
X140.5Y-76.0
T2
X103.0Y-25.5
X103.0Y-73.0
X157.5Y-25.5
X157.5Y-72.5
T3
X105.15Y-53.11
X105.15Y-64.54
M30
