M48
; DRILL file KiCad 10.0.6 date 2026-10-07T06:58:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T06:58:35+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
%
G90
G05
T1
X145.4Y-92.0
X145.4Y-114.0
T2
X110.84Y-58.65
X122.27Y-58.65
T3
X55.0Y-55.0
X55.0Y-125.0
X145.0Y-55.0
X145.0Y-125.0
M30
