M48
; DRILL file KiCad 10.0.5 date 2026-10-09T23:30:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-09T23:30:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X70.5Y-90.0
X85.5Y-90.0
T2
X59.0Y-50.0
X59.0Y-91.0
X68.07Y-55.0
X79.5Y-55.0
X96.0Y-50.0
X96.0Y-91.0
M30
